"use client";

import { useState } from "react";
import { jsPDF } from "jspdf";
import { Upload, LayoutGrid, List, Search, FilePlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DocumentCard } from "./document-card";
import { DocumentUploadModal } from "./document-upload-modal";
import { DocumentDetailModal } from "./document-detail-modal";
import { DocumentGeneratorModal } from "./document-generator-modal";
import { SuggestedDocumentsWidget } from "./suggested-documents-widget";
import { useDocuments, useGeneratedDocuments, useUploadDocument, useDeleteDocument } from "../hooks/use-documents-query";
import type { UploadDocumentInput } from "../api/documents-api";
import { DOC_TYPE_LABELS_GEN } from "../api/document-generation";
import type { DocType, AppDocument } from "../types/documents.types";
import { SetupOverlay } from "@/features/billing/components/setup-overlay";
import { isInSetupMode } from "@/features/billing/api/setup-check";
import { trackEvent } from "@/features/assessments/api/assessment-api";
import { useHasBusiness } from "@/features/businesses/hooks/use-has-business";
import { EmptyBusinessState } from "@/features/businesses/components/empty-business-state";
import styles from "./document-library.module.css";

/** Generates a PDF and triggers download directly */
function downloadAsPdf(title: string, content: string) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "pt",
    format: "a4"
  });
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(title, 40, 40);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated by LaunchSafe - ${new Date().toLocaleDateString()}`, 40, 60);

  doc.setTextColor(0);
  doc.setFontSize(12);
  
  const splitContent = doc.splitTextToSize(content, 515); // A4 width is ~595pt, minus 80pt margins
  
  let y = 90;
  for (let i = 0; i < splitContent.length; i++) {
    if (y > 780) { // A4 height is ~842pt, leave bottom margin
      doc.addPage();
      y = 40;
    }
    doc.text(splitContent[i], 40, y);
    y += 14;
  }
  
  const safeFilename = title.replace(/[^a-zA-Z0-9]/g, '_') + ".pdf";
  const blob = doc.output('blob');
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.style.display = "none";
  a.href = url;
  a.download = safeFilename;
  document.body.appendChild(a);
  a.click();
  window.URL.revokeObjectURL(url);
  document.body.removeChild(a);
}

type ViewMode = "table" | "card";
type FilterKey = "all" | DocType;

const FILTERS: { key: FilterKey; label: string }[] = [
  { key: "all", label: "All Documents" },
  { key: "cac_certificate", label: "Certificates" },
  { key: "business_permit", label: "Permits" },
  { key: "operating_license", label: "Licenses" },
  { key: "inspection_report", label: "Reports" },
  { key: "policy_document", label: "Policies" },
  { key: "other", label: "Other" },
];

export function DocumentLibrary() {
  const [view, setView] = useState<ViewMode>("card");
  const [filter, setFilter] = useState<FilterKey>("all");
  const [search, setSearch] = useState("");
  const [showUpload, setShowUpload] = useState(false);
  const [showGenerate, setShowGenerate] = useState(false);
  const [selectedDoc, setSelectedDoc] = useState<AppDocument | null>(null);
  const [deleteConfirmId, setDeleteConfirmId] = useState<string | null>(null);
  const hasBusiness = useHasBusiness();

  const { data: uploadedDocs = [], isLoading: isLoadingDocs, refetch: refetchDocs } = useDocuments();
  const { data: generatedDocs = [], isLoading: isLoadingGen, refetch: refetchGen } = useGeneratedDocuments();
  
  const uploadMutation = useUploadDocument();
  const deleteMutation = useDeleteDocument();

  const allGenerated = generatedDocs.map(g => ({
    id: g.id,
    businessId: g.businessId,
    userId: g.userId,
    title: g.title,
    description: DOC_TYPE_LABELS_GEN[g.documentType] || g.documentType,
    docType: "other" as DocType,
    fileUrl: null,
    fileName: `${g.title}.pdf`,
    fileSize: g.content?.length || 0,
    fileType: "application/pdf",
    uploadedBy: "System",
    uploadedAt: g.createdAt,
    updatedAt: g.updatedAt,
    expiryDate: null,
    issuingAgency: null,
    verificationStatus: null,
    renewalDate: null,
    tags: [],
    content: g.content,
  }));

  const allItems = [...uploadedDocs, ...allGenerated];

  const filtered = (() => {
    let result = allItems;
    if (filter !== "all") {
      result = result.filter((d: any) => d.docType === filter);
    }
    if (search.trim()) {
      const q = search.toLowerCase();
      result = result.filter((d: any) => d.title.toLowerCase().includes(q));
    }
    return result;
  })();

  function refresh() {
    refetchDocs();
    refetchGen();
  }

  function handleUpload(input: UploadDocumentInput) {
    return uploadMutation.mutateAsync(input, {
      onSuccess: () => {
        trackEvent("Document Uploaded", { title: input.title });
        setShowUpload(false);
      }
    });
  }

  function handleDelete(id: string) {
    deleteMutation.mutate(id, {
      onSuccess: () => {
        trackEvent("Document Deleted", { id });
        setSelectedDoc(null);
        setDeleteConfirmId(null);
      }
    });
  }

  async function handleDownload(doc: AppDocument) {
    if (doc.fileUrl) {
      try {
        const res = await fetch(doc.fileUrl);
        const blob = await res.blob();
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.style.display = "none";
        a.href = url;
        a.download = doc.fileName || "document";
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
        trackEvent("Document Downloaded", { id: doc.id });
      } catch (err) {
        // Fallback if CORS prevents blob fetch
        window.open(doc.fileUrl, '_blank');
        trackEvent("Document Downloaded", { id: doc.id });
      }
    } else if (doc.content && doc.uploadedBy === "System") {
      // Generated document — create a PDF directly
      downloadAsPdf(doc.title, doc.content);
      trackEvent("Document Downloaded", { id: doc.id });
    } else {
      // Fallback for missing storage files
      alert("This document's file could not be found or the upload did not complete successfully.");
    }
  }

  const isLoading = isLoadingDocs || isLoadingGen;

  return (
    <SetupOverlay>
    <div className={styles.page}>
      {!isInSetupMode() && hasBusiness === false ? (
        <EmptyBusinessState />
      ) : (
        <>
          <div className={styles.header}>
        <div>
          <h1 className={styles.title}>Documents</h1>
          <p className={styles.subtitle}>Manage your compliance documents and records.</p>
        </div>
        <div style={{ display: "flex", gap: 8 }}>
          <Button variant="outline" size="md" onClick={() => setShowGenerate(true)}><FilePlus size={16} /> Generate</Button>
          <Button variant="primary" size="md" onClick={() => setShowUpload(true)}><Upload size={16} /> Upload</Button>
        </div>
      </div>

      <div className={styles.toolbar}>
        <div className={styles.searchWrap}>
          <Search size={16} className={styles.searchIcon} />
          <input className={styles.search} placeholder="Search documents..." value={search} onChange={(e) => setSearch(e.target.value)} />
        </div>
        <div className={styles.viewToggle}>
          <button type="button" className={`${styles.viewBtn} ${view === "card" ? styles.viewActive : ""}`} onClick={() => setView("card")} aria-label="Card view"><LayoutGrid size={16} /></button>
          <button type="button" className={`${styles.viewBtn} ${view === "table" ? styles.viewActive : ""}`} onClick={() => setView("table")} aria-label="Table view"><List size={16} /></button>
        </div>
      </div>

      <div className={styles.filters}>
        {FILTERS.map((f) => (
          <button key={f.key} className={`${styles.filterBtn} ${filter === f.key ? styles.filterActive : ""}`} onClick={() => setFilter(f.key)}>
            {f.label}
          </button>
        ))}
      </div>

      {isLoading ? (
        <div style={{ padding: "48px 0", textAlign: "center", color: "var(--color-role-light-onSurfaceVariant)" }}>
          Loading documents...
        </div>
      ) : filtered.length > 0 ? (
        view === "table" ? (
          <div className={styles.table}>
            <div className={styles.tableHeader}>
              <span className={styles.th}>Name</span>
              <span className={styles.th}>Type</span>
              <span className={styles.th}>Size</span>
              <span className={styles.th}>Date</span>
              <span className={styles.th} style={{ textAlign: "right" }}>Actions</span>
            </div>
            {filtered.map((d) => <DocumentCard key={d.id} doc={d} onView={setSelectedDoc} onDownload={handleDownload} onDelete={handleDelete} isDeleting={deleteMutation.isPending && deleteMutation.variables === d.id} viewMode="table" />)}
          </div>
        ) : (
          <div className={styles.grid}>
            {filtered.map((d) => <DocumentCard key={d.id} doc={d} onView={setSelectedDoc} onDownload={handleDownload} onDelete={handleDelete} isDeleting={deleteMutation.isPending && deleteMutation.variables === d.id} viewMode="card" />)}
          </div>
        )
      ) : (
        <div className={styles.empty}>
          <p className={styles.emptyText}>
            {allItems.length === 0 ? "No documents yet. Upload or generate a document to get started." : "No matching documents found."}
          </p>
          {allItems.length === 0 && (
            <div style={{ display: "flex", gap: 8 }}>
              <Button variant="primary" size="md" onClick={() => setShowUpload(true)}>Upload Document</Button>
              <Button variant="outline" size="md" onClick={() => setShowGenerate(true)}>Generate Document</Button>
            </div>
          )}
              {allItems.length > 0 && <Button variant="ghost" size="sm" onClick={() => { setFilter("all"); setSearch(""); }}>Clear Filters</Button>}
        </div>
      )}

      <SuggestedDocumentsWidget onUpload={(title, docType) => {
        setShowUpload(true);
      }} />

      {showUpload && <DocumentUploadModal onSave={handleUpload} onClose={() => setShowUpload(false)} />}
      {showGenerate && <DocumentGeneratorModal onClose={() => setShowGenerate(false)} onComplete={refresh} />}
      {selectedDoc && (
        <DocumentDetailModal
          doc={selectedDoc}
          onUpdate={refresh}
          onDelete={handleDelete}
          onDownload={handleDownload}
          onClose={() => setSelectedDoc(null)}
          isDeleting={deleteMutation.isPending && deleteMutation.variables === selectedDoc.id}
        />
      )}
        </>
      )}
    </div>
    </SetupOverlay>
  );
}
